swagger: '2.0'
info:
  description: The Star Wars API is the world's first quantified and programmatically-formatted set of Star Wars data.
  title: Star Wars API
  version: "1.0.0"
  termsOfService: 'https://swapi.co/about'
  contact:
    name: not sure
    url: not sure
  license:
    name: BSD License
    url: not sure license url
paths:
  /planets/{id}:
    get:
      description: Get a specific planets resource.
      summary: Get a specific planets resource.
      parameters:
        - name: id
          in: path
          description: ID of planet.
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Planet'
            # $ref: 'http://swapi.co/api/planets/schema'
        404:
          description: NOT FOUND
definitions:
  Planet:
    type: object
    properties:
      name:
        type: string
        description: The name of this planet.
      diameter:
        type: string
        description: The diameter of this planet in kilometers.  
      rotation_period:
        type: string
        description: The number of standard hours it takes for this planet to complete a single rotation on its axis.
      orbital_period:
        type: string
        description: The number of standard days it takes for this planet to complete a single orbit of its local star.
      climate:
        type: string
        description: The climate of this planet. Comma separated if diverse.
      gravity:
        type: string
        description: A number denoting the gravity of this planet, where "1" is normal or 1 standard G. "2" is twice or 2 standard Gs. "0.5" is half or 0.5 standard Gs.
      terrain:
        type: string
        description: The terrain of this planet. Comma separated if diverse.
      surface_water:
        type: string
        description: The percentage of the planet surface that is naturally occurring water or bodies of water.
      population:
        type: string
        description: The average population of sentient beings inhabiting this planet.
      created:
        type: string
        format: date-time
        description: The ISO 8601 date format of the time that this resource was created.
      updated:
        type: string
        format: date-time
        description: The ISO 8601 date format of the time that this resource was edited.
    example:
      name: "Tatooine"
      diameter: "10465"
      rotation_period: "23"
      orbital_period: "304"
      climate: "arid"
      gravity: "1 standard"
      terrain: "desert"
      surface_water: "1"
      population: "200000"
      created: "2014-12-09T13:50:49.641000Z"
      updated: "2014-12-21T20:48:04.175778Z"